# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [2]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
from pprint import pprint

# Import API key
from api_keys import g_key

#configure gmap
gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [3]:
csv_file_df = pd.read_csv("Data.csv")
csv_file_df.head()

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp(C),Wind Speed
0,Fortuna,20,US,1569548205,77,40.60,-124.16,18.33,5.10
1,Sarkand,99,KZ,1569548205,27,45.41,79.91,17.64,2.71
2,Iqaluit,90,CA,1569548205,80,63.75,-68.52,4.00,11.80
3,Dafeng,100,CN,1569548205,52,33.20,120.46,24.54,2.43
4,Rikitea,39,PF,1569548206,71,-23.12,-134.97,22.14,4.70

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [4]:
csv_file_df.dropna()
csv_file_df.head()

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp(C),Wind Speed
0,Fortuna,20,US,1569548205,77,40.60,-124.16,18.33,5.10
1,Sarkand,99,KZ,1569548205,27,45.41,79.91,17.64,2.71
2,Iqaluit,90,CA,1569548205,80,63.75,-68.52,4.00,11.80
3,Dafeng,100,CN,1569548205,52,33.20,120.46,24.54,2.43
4,Rikitea,39,PF,1569548206,71,-23.12,-134.97,22.14,4.70

In [5]:
locations = csv_file_df[["Lat", "Lng"]]
new_york_coordinates = (40.75, -74.00)
fig = gmaps.figure(center=new_york_coordinates, zoom_level=2)
heat_layer = gmaps.heatmap_layer(locations, weights=csv_file_df["Humidity"], dissipating=False, max_intensity=10, point_radius=2)

#Add layer
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [6]:
chosen_pd = csv_file_df[csv_file_df["Humidity"]<=50]
chosen_pd

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp(C),Wind Speed
1,Sarkand,99,KZ,1569548205,27,45.41,79.91,17.64,2.71
14,Tymovskoye,0,RU,1569548207,39,50.85,142.66,15.94,3.06
26,San Carlos de Bariloche,0,AR,1569548093,41,-41.13,-71.31,15.00,2.10
27,Grootfontein,0,NaN,1569548209,33,-19.56,18.10,8.34,4.25
30,Jamestown,0,AU,1569548209,33,-33.21,138.60,21.84,6.71
34,Yumen,0,CN,1569548210,10,40.29,97.04,24.14,2.91
40,Mar del Plata,100,AR,1569548211,43,-46.43,-67.52,12.84,7.65
48,Bluff,0,AU,1569548212,31,-23.58,149.07,28.54,3.02
51,Cherskiy,3,RU,1569548213,39,68.75,161.30,4.14,2.80
54,Karratha,0,AU,1569548213,15,-20.74,116.85,29.74,4.10
55,Ilulissat,0,GL,1569548214,35,69.22,-51.10,4.00,4.60
56,East London,0,ZA,1569548049,17,-33.02,27.91,18.14,2.24
59,Codrington,6,AU,1569548214,50,-28.95,153.24,27.00,4.10
60,Nemuro,20,JP,1569548214,42,43.32,145.57,19.00,0.50
65,Chifeng,32,CN,1569548215,21,42.27,118.96,21.94,3.35
66,Kroya,57,ID,1569548215,33,-6.50,108.06,34.24,3.68
67,Santiago del Estero,0,AR,1569548216,36,-27.80,-64.26,20.04,4.25
72,Busselton,94,AU,1569547962,47,-33.64,115.35,18.33,2.90
77,Harper,1,US,1569548217,45,30.30,-99.24,29.00,6.05
89,Birjand,0,IR,1569548219,13,32.86,59.22,21.00,6.20
90,West Wendover,1,US,1569548219,25,40.74,-114.07,25.00,3.65
91,Yulara,0,AU,1569548219,20,-25.24,130.99,29.00,2.60
94,Carnarvon,0,ZA,1569548196,18,-30.97,22.13,10.24,2.32
106,Luderitz,99,NaN,1569548222,37,-26.65,15.16,22.00,0.50
107,Tucumcari,1,US,1569548222,30,35.17,-103.73,27.00,4.60
113,Airai,0,TL,1569548223,46,-8.93,125.41,30.24,2.42
133,Arman,1,RU,1569548227,46,59.70,150.17,3.44,3.17
140,Riachao das Neves,3,BR,1569548224,30,-11.75,-44.91,22.14,1.12
151,Atwater,75,US,1569548229,40,37.35,-120.61,30.00,5.70
160,Nerchinskiy Zavod,1,RU,1569548231,41,51.31,119.61,18.24,5.04
...,...,...,...,...,...,...,...,...,...
353,Central Point,1,US,1569548263,32,42.38,-122.91,28.00,4.10
358,La Rioja,0,AR,1569548264,39,-29.41,-66.86,16.44,2.40
380,Bafq,0,IR,1569548268,12,31.60,55.40,20.04,1.66
381,Katobu,70,ID,1569548268,44,-4.94,122.53,32.34,3.17
383,Alice Springs,0,AU,1569548268,26,-23.70,133.88,27.00,2.10
387,Jalu,0,LY,1569548269,50,29.03,21.55,21.94,2.86
420,Caldwell,1,US,1569548274,35,43.67,-116.69,25.00,2.10
422,Vardo,1,US,1569548275,49,39.62,-77.74,22.00,3.60
423,Hervey Bay,40,AU,1569548275,47,-25.30,152.85,25.00,5.10
426,Digby,33,CA,1569548275,1,44.62,-65.76,16.11,1.34
435,Adrar,0,DZ,1569548277,9,27.87,-0.29,30.00,3.60
439,Kargil,0,PK,1569548278,43,34.56,76.13,9.64,2.31
440,Sar-e Pul,0,AF,1569548278,18,36.22,65.93,26.24,0.80
444,Aranos,0,NaN,1569548279,24,-24.14,19.11,9.24,5.03
456,San Rafael,82,AR,1569548281,32,-34.61,-68.33,19.14,1.97
459,Flinders,0,AU,1569548281,24,-34.58,150.85,23.33,7.70
463,Kerman,0,IR,1569548282,14,30.29,57.06,15.00,1.00
483,Mehran,0,IR,1569548285,28,33.12,46.17,21.00,2.10
492,Madang,0,CN,1569548287,42,35.32,102.79,8.64,1.84
493,Pishin,0,PK,1569548287,44,30.58,67.00,22.64,0.35
503,Mecca,0,SA,1569548023,14,21.43,39.83,29.44,3.53
504,Beyneu,93,KZ,1569548289,35,45.32,55.19,11.14,7.26
507,Aswan,0,EG,1569548289,17,24.09,32.90,28.00,2.60
512,Xiangxiang,36,CN,1569548290,33,27.73,112.52,30.04,2.31
520,Katherine,0,AU,1569548291,31,-14.47,132.26,32.00,4.10
524,Herat,0,AF,1569548292,23,34.35,62.22,17.00,0.84
529,Mayo,75,CA,1569548293,36,63.59,-135.90,9.00,4.10
535,San Angelo,1,US,1569548014,36,31.46,-100.44,33.00,4.60
541,Noumea,75,NC,1569548000,42,-22.28,166.46,27.00,6.20
549,Baruun-Urt,49,MN,1569548296,25,46.68,113.28,21.34,9.92

In [7]:
chosen_pd.dropna()

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp(C),Wind Speed
1,Sarkand,99,KZ,1569548205,27,45.41,79.91,17.64,2.71
14,Tymovskoye,0,RU,1569548207,39,50.85,142.66,15.94,3.06
26,San Carlos de Bariloche,0,AR,1569548093,41,-41.13,-71.31,15.00,2.10
30,Jamestown,0,AU,1569548209,33,-33.21,138.60,21.84,6.71
34,Yumen,0,CN,1569548210,10,40.29,97.04,24.14,2.91
40,Mar del Plata,100,AR,1569548211,43,-46.43,-67.52,12.84,7.65
48,Bluff,0,AU,1569548212,31,-23.58,149.07,28.54,3.02
51,Cherskiy,3,RU,1569548213,39,68.75,161.30,4.14,2.80
54,Karratha,0,AU,1569548213,15,-20.74,116.85,29.74,4.10
55,Ilulissat,0,GL,1569548214,35,69.22,-51.10,4.00,4.60
56,East London,0,ZA,1569548049,17,-33.02,27.91,18.14,2.24
59,Codrington,6,AU,1569548214,50,-28.95,153.24,27.00,4.10
60,Nemuro,20,JP,1569548214,42,43.32,145.57,19.00,0.50
65,Chifeng,32,CN,1569548215,21,42.27,118.96,21.94,3.35
66,Kroya,57,ID,1569548215,33,-6.50,108.06,34.24,3.68
67,Santiago del Estero,0,AR,1569548216,36,-27.80,-64.26,20.04,4.25
72,Busselton,94,AU,1569547962,47,-33.64,115.35,18.33,2.90
77,Harper,1,US,1569548217,45,30.30,-99.24,29.00,6.05
89,Birjand,0,IR,1569548219,13,32.86,59.22,21.00,6.20
90,West Wendover,1,US,1569548219,25,40.74,-114.07,25.00,3.65
91,Yulara,0,AU,1569548219,20,-25.24,130.99,29.00,2.60
94,Carnarvon,0,ZA,1569548196,18,-30.97,22.13,10.24,2.32
107,Tucumcari,1,US,1569548222,30,35.17,-103.73,27.00,4.60
113,Airai,0,TL,1569548223,46,-8.93,125.41,30.24,2.42
133,Arman,1,RU,1569548227,46,59.70,150.17,3.44,3.17
140,Riachao das Neves,3,BR,1569548224,30,-11.75,-44.91,22.14,1.12
151,Atwater,75,US,1569548229,40,37.35,-120.61,30.00,5.70
160,Nerchinskiy Zavod,1,RU,1569548231,41,51.31,119.61,18.24,5.04
166,Xining,0,CN,1569548232,42,36.62,101.77,20.00,2.37
176,Muli,0,CN,1569548234,43,28.08,109.56,26.84,1.32
...,...,...,...,...,...,...,...,...,...
352,Atbasar,100,KZ,1569548263,50,51.81,68.36,5.64,1.25
353,Central Point,1,US,1569548263,32,42.38,-122.91,28.00,4.10
358,La Rioja,0,AR,1569548264,39,-29.41,-66.86,16.44,2.40
380,Bafq,0,IR,1569548268,12,31.60,55.40,20.04,1.66
381,Katobu,70,ID,1569548268,44,-4.94,122.53,32.34,3.17
383,Alice Springs,0,AU,1569548268,26,-23.70,133.88,27.00,2.10
387,Jalu,0,LY,1569548269,50,29.03,21.55,21.94,2.86
420,Caldwell,1,US,1569548274,35,43.67,-116.69,25.00,2.10
422,Vardo,1,US,1569548275,49,39.62,-77.74,22.00,3.60
423,Hervey Bay,40,AU,1569548275,47,-25.30,152.85,25.00,5.10
426,Digby,33,CA,1569548275,1,44.62,-65.76,16.11,1.34
435,Adrar,0,DZ,1569548277,9,27.87,-0.29,30.00,3.60
439,Kargil,0,PK,1569548278,43,34.56,76.13,9.64,2.31
440,Sar-e Pul,0,AF,1569548278,18,36.22,65.93,26.24,0.80
456,San Rafael,82,AR,1569548281,32,-34.61,-68.33,19.14,1.97
459,Flinders,0,AU,1569548281,24,-34.58,150.85,23.33,7.70
463,Kerman,0,IR,1569548282,14,30.29,57.06,15.00,1.00
483,Mehran,0,IR,1569548285,28,33.12,46.17,21.00,2.10
492,Madang,0,CN,1569548287,42,35.32,102.79,8.64,1.84
493,Pishin,0,PK,1569548287,44,30.58,67.00,22.64,0.35
503,Mecca,0,SA,1569548023,14,21.43,39.83,29.44,3.53
504,Beyneu,93,KZ,1569548289,35,45.32,55.19,11.14,7.26
507,Aswan,0,EG,1569548289,17,24.09,32.90,28.00,2.60
512,Xiangxiang,36,CN,1569548290,33,27.73,112.52,30.04,2.31
520,Katherine,0,AU,1569548291,31,-14.47,132.26,32.00,4.10
524,Herat,0,AF,1569548292,23,34.35,62.22,17.00,0.84
529,Mayo,75,CA,1569548293,36,63.59,-135.90,9.00,4.10
535,San Angelo,1,US,1569548014,36,31.46,-100.44,33.00,4.60
541,Noumea,75,NC,1569548000,42,-22.28,166.46,27.00,6.20
549,Baruun-Urt,49,MN,1569548296,25,46.68,113.28,21.34,9.92

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [8]:
hotels_df = chosen_pd[["City", "Country", "Lat", "Lng", "Humidity"]]
hotels_df.head()

                       City Country    Lat     Lng  Humidity
1                   Sarkand      KZ  45.41   79.91        27
14               Tymovskoye      RU  50.85  142.66        39
26  San Carlos de Bariloche      AR -41.13  -71.31        41
27             Grootfontein     NaN -19.56   18.10        33
30                Jamestown      AU -33.21  138.60        33

In [9]:
hotels_df["Hotel Name"]= ""
hotels_df.head()

/Users/Deborah/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

                       City Country    Lat     Lng  Humidity Hotel Name
1                   Sarkand      KZ  45.41   79.91        27
14               Tymovskoye      RU  50.85  142.66        39
26  San Carlos de Bariloche      AR -41.13  -71.31        41
27             Grootfontein     NaN -19.56   18.10        33
30                Jamestown      AU -33.21  138.60        33

In [13]:
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
#print(requests.get(base_url).json())
params = {"radius": 5000,
            "type": "hotels",
         "key": g_key}
hotel_names = []
for index, row in hotels_df.iterrows():
    params["location"]= f'{row["Lat"]},{row["Lng"]}'
    response = requests.get(base_url, params =params).json()
    
    results = response["results"]
    hotels_df.loc[index, "Hotel Name"] = results[0]['name']
#print(results)
    #hotel_names.append(response["results"][0]["name"])
#print(hotel_names)

In [14]:

#hotels_df.loc[index, "Hotel Name"] = results[0]['name']
hotels_df.head(50)

,City,Country,Lat,Lng,Humidity,Hotel Name
1,Sarkand,KZ,45.41,79.91,27,Sarķand
14,Tymovskoye,RU,50.85,142.66,39,Tymovskoye
26,San Carlos de Bariloche,AR,-41.13,-71.31,41,San Carlos de Bariloche
27,Grootfontein,NaN,-19.56,18.10,33,Grootfontein
30,Jamestown,AU,-33.21,138.60,33,Jamestown
34,Yumen,CN,40.29,97.04,10,Jiuquan
40,Mar del Plata,AR,-46.43,-67.52,43,Caleta Olivia
48,Bluff,AU,-23.58,149.07,31,Bluff
51,Cherskiy,RU,68.75,161.30,39,Chersky
54,Karratha,AU,-20.74,116.85,15,Karratha
55,Ilulissat,GL,69.22,-51.10,35,Ilulissat
56,East London,ZA,-33.02,27.91,17,East London
59,Codrington,AU,-28.95,153.24,50,Coraki
60,Nemuro,JP,43.32,145.57,42,Nemuro
65,Chifeng,CN,42.27,118.96,21,Chifeng
66,Kroya,ID,-6.50,108.06,33,Majelis Tarbiyatul Aulad Kroya
67,Santiago del Estero,AR,-27.80,-64.26,36,Santiago del Estero
72,Busselton,AU,-33.64,115.35,47,Busselton
77,Harper,US,30.30,-99.24,45,Harper
89,Birjand,IR,32.86,59.22,13,Birjand
90,West Wendover,US,40.74,-114.07,25,Wendover
91,Yulara,AU,-25.24,130.99,20,Petermann
94,Carnarvon,ZA,-30.97,22.13,18,Carnarvon
106,Luderitz,NaN,-26.65,15.16,37,Luderitz
107,Tucumcari,US,35.17,-103.73,30,Tucumcari
113,Airai,TL,-8.93,125.41,46,Atsabe
133,Arman,RU,59.70,150.17,46,Arman'
140,Riachao das Neves,BR,-11.75,-44.91,30,Riachão das Neves
151,Atwater,US,37.35,-120.61,40,Atwater
160,Nerchinskiy Zavod,RU,51.31,119.61,41,Nerchinsky Zavod
166,Xining,CN,36.62,101.77,42,Xining
176,Muli,CN,28.08,109.56,43,Xiangxi
179,Pozo Colorado,PY,-23.49,-58.80,37,Pozo Colorado
185,Bitung,ID,1.44,125.19,43,Bitung
196,Opuwo,NaN,-18.06,13.84,40,Opuwo
198,Alihe,CN,50.57,123.73,30,Hulun Buir
203,Tessalit,ML,20.20,1.01,10,Achemelmel
211,Sabha,LY,27.03,14.43,33,Sabhā
213,Port Hedland,AU,-20.31,118.58,28,Port Hedland
214,Saint Anthony,US,43.97,-111.68,25,Saint Anthony
215,Dongsheng,CN,29.72,112.52,33,Jingzhou
216,Henties Bay,NaN,-22.12,14.28,49,Hentiesbaai
222,Umm Kaddadah,SD,13.60,26.69,50,Umm Kadadda
226,San Juan,AR,-31.54,-68.53,42,San Juan
249,Boyolangu,ID,-8.09,111.90,47,Tulungagung
250,Saint-Donat-de-Montcalm,CA,46.32,-74.22,9,Saint-Donat
254,Genhe,CN,50.78,121.52,34,Hulun Buir
274,Mount Isa,AU,-20.73,139.49,20,Mount Isa
280,Zhezkazgan,KZ,47.80,67.71,50,Zhezqazghan
282,Atar,MR,20.52,-13.05,15,Atar

In [15]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotels_df.iterrows()]
#hotel_info = [info_box_template.format(**row) for index, row in narrowed_city_df.iterrows()]
locations = hotels_df[["Lat", "Lng"]]

In [20]:
# Add marker layer ontop of heat map

#new_york_coordinates = (40.75, -74.00)
#fig = gmaps.figure(center=new_york_coordinates, zoom_level=2)
#heat_layer = gmaps.heatmap_layer(locations, weights="Humidity", dissipating=False, max_intensity=10, point_radius=2)

#Add layer
#fig.add_layer(heat_layer)
#fig

figure_layout = {'width': '400px',
                'height': '300px',
                'border': '1px solid black',
                'padding': '1px',
                'margin': '0 auto 0 auto'}
fig =gmaps.figure(layout=figure_layout)
markers =gmaps.marker_layer(locations, info_box_content= hotel_info)
fig.add_layer(markers)
# Display Map
#fig

#fig =gmaps.figure()
fig.add_layer(heat_layer)
#fig.add_layers(markers)
fig

Figure(layout=FigureLayout(border='1px solid black', height='300px', margin='0 auto 0 auto', padding='1px', wi…