# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
from pprint import pprint

# Import API key
from api_keys import g_key

#configure gmap
gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
csv_file_df = pd.read_csv("Data.csv")
csv_file_df.head()

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp(C),Wind Speed
0,Fortuna,20,US,1569548205,77,40.60,-124.16,18.33,5.10
1,Sarkand,99,KZ,1569548205,27,45.41,79.91,17.64,2.71
2,Iqaluit,90,CA,1569548205,80,63.75,-68.52,4.00,11.80
3,Dafeng,100,CN,1569548205,52,33.20,120.46,24.54,2.43
4,Rikitea,39,PF,1569548206,71,-23.12,-134.97,22.14,4.70

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
csv_file_df.dropna()
csv_file_df.head()

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp(C),Wind Speed
0,Fortuna,20,US,1569548205,77,40.60,-124.16,18.33,5.10
1,Sarkand,99,KZ,1569548205,27,45.41,79.91,17.64,2.71
2,Iqaluit,90,CA,1569548205,80,63.75,-68.52,4.00,11.80
3,Dafeng,100,CN,1569548205,52,33.20,120.46,24.54,2.43
4,Rikitea,39,PF,1569548206,71,-23.12,-134.97,22.14,4.70

In [4]:
locations = csv_file_df[["Lat", "Lng"]]
new_york_coordinates = (40.75, -74.00)
fig = gmaps.figure(center=new_york_coordinates, zoom_level=2)
heat_layer = gmaps.heatmap_layer(locations, weights=csv_file_df["Humidity"], dissipating=False, max_intensity=10, point_radius=2)

#Add layer
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [16]:
chosen_pd = csv_file_df[csv_file_df["Humidity"]<=50]
chosen_pd

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp(C),Wind Speed
1,Sarkand,99,KZ,1569548205,27,45.41,79.91,17.64,2.71
14,Tymovskoye,0,RU,1569548207,39,50.85,142.66,15.94,3.06
26,San Carlos de Bariloche,0,AR,1569548093,41,-41.13,-71.31,15.00,2.10
27,Grootfontein,0,NaN,1569548209,33,-19.56,18.10,8.34,4.25
30,Jamestown,0,AU,1569548209,33,-33.21,138.60,21.84,6.71
34,Yumen,0,CN,1569548210,10,40.29,97.04,24.14,2.91
40,Mar del Plata,100,AR,1569548211,43,-46.43,-67.52,12.84,7.65
48,Bluff,0,AU,1569548212,31,-23.58,149.07,28.54,3.02
51,Cherskiy,3,RU,1569548213,39,68.75,161.30,4.14,2.80
54,Karratha,0,AU,1569548213,15,-20.74,116.85,29.74,4.10
55,Ilulissat,0,GL,1569548214,35,69.22,-51.10,4.00,4.60
56,East London,0,ZA,1569548049,17,-33.02,27.91,18.14,2.24
59,Codrington,6,AU,1569548214,50,-28.95,153.24,27.00,4.10
60,Nemuro,20,JP,1569548214,42,43.32,145.57,19.00,0.50
65,Chifeng,32,CN,1569548215,21,42.27,118.96,21.94,3.35
66,Kroya,57,ID,1569548215,33,-6.50,108.06,34.24,3.68
67,Santiago del Estero,0,AR,1569548216,36,-27.80,-64.26,20.04,4.25
72,Busselton,94,AU,1569547962,47,-33.64,115.35,18.33,2.90
77,Harper,1,US,1569548217,45,30.30,-99.24,29.00,6.05
89,Birjand,0,IR,1569548219,13,32.86,59.22,21.00,6.20
90,West Wendover,1,US,1569548219,25,40.74,-114.07,25.00,3.65
91,Yulara,0,AU,1569548219,20,-25.24,130.99,29.00,2.60
94,Carnarvon,0,ZA,1569548196,18,-30.97,22.13,10.24,2.32
106,Luderitz,99,NaN,1569548222,37,-26.65,15.16,22.00,0.50
107,Tucumcari,1,US,1569548222,30,35.17,-103.73,27.00,4.60
113,Airai,0,TL,1569548223,46,-8.93,125.41,30.24,2.42
133,Arman,1,RU,1569548227,46,59.70,150.17,3.44,3.17
140,Riachao das Neves,3,BR,1569548224,30,-11.75,-44.91,22.14,1.12
151,Atwater,75,US,1569548229,40,37.35,-120.61,30.00,5.70
160,Nerchinskiy Zavod,1,RU,1569548231,41,51.31,119.61,18.24,5.04
...,...,...,...,...,...,...,...,...,...
353,Central Point,1,US,1569548263,32,42.38,-122.91,28.00,4.10
358,La Rioja,0,AR,1569548264,39,-29.41,-66.86,16.44,2.40
380,Bafq,0,IR,1569548268,12,31.60,55.40,20.04,1.66
381,Katobu,70,ID,1569548268,44,-4.94,122.53,32.34,3.17
383,Alice Springs,0,AU,1569548268,26,-23.70,133.88,27.00,2.10
387,Jalu,0,LY,1569548269,50,29.03,21.55,21.94,2.86
420,Caldwell,1,US,1569548274,35,43.67,-116.69,25.00,2.10
422,Vardo,1,US,1569548275,49,39.62,-77.74,22.00,3.60
423,Hervey Bay,40,AU,1569548275,47,-25.30,152.85,25.00,5.10
426,Digby,33,CA,1569548275,1,44.62,-65.76,16.11,1.34
435,Adrar,0,DZ,1569548277,9,27.87,-0.29,30.00,3.60
439,Kargil,0,PK,1569548278,43,34.56,76.13,9.64,2.31
440,Sar-e Pul,0,AF,1569548278,18,36.22,65.93,26.24,0.80
444,Aranos,0,NaN,1569548279,24,-24.14,19.11,9.24,5.03
456,San Rafael,82,AR,1569548281,32,-34.61,-68.33,19.14,1.97
459,Flinders,0,AU,1569548281,24,-34.58,150.85,23.33,7.70
463,Kerman,0,IR,1569548282,14,30.29,57.06,15.00,1.00
483,Mehran,0,IR,1569548285,28,33.12,46.17,21.00,2.10
492,Madang,0,CN,1569548287,42,35.32,102.79,8.64,1.84
493,Pishin,0,PK,1569548287,44,30.58,67.00,22.64,0.35
503,Mecca,0,SA,1569548023,14,21.43,39.83,29.44,3.53
504,Beyneu,93,KZ,1569548289,35,45.32,55.19,11.14,7.26
507,Aswan,0,EG,1569548289,17,24.09,32.90,28.00,2.60
512,Xiangxiang,36,CN,1569548290,33,27.73,112.52,30.04,2.31
520,Katherine,0,AU,1569548291,31,-14.47,132.26,32.00,4.10
524,Herat,0,AF,1569548292,23,34.35,62.22,17.00,0.84
529,Mayo,75,CA,1569548293,36,63.59,-135.90,9.00,4.10
535,San Angelo,1,US,1569548014,36,31.46,-100.44,33.00,4.60
541,Noumea,75,NC,1569548000,42,-22.28,166.46,27.00,6.20
549,Baruun-Urt,49,MN,1569548296,25,46.68,113.28,21.34,9.92

In [6]:
chosen_pd.dropna()

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp(C),Wind Speed
1,Sarkand,99,KZ,1569548205,27,45.41,79.91,17.64,2.71
14,Tymovskoye,0,RU,1569548207,39,50.85,142.66,15.94,3.06
26,San Carlos de Bariloche,0,AR,1569548093,41,-41.13,-71.31,15.00,2.10
30,Jamestown,0,AU,1569548209,33,-33.21,138.60,21.84,6.71
34,Yumen,0,CN,1569548210,10,40.29,97.04,24.14,2.91
40,Mar del Plata,100,AR,1569548211,43,-46.43,-67.52,12.84,7.65
48,Bluff,0,AU,1569548212,31,-23.58,149.07,28.54,3.02
51,Cherskiy,3,RU,1569548213,39,68.75,161.30,4.14,2.80
54,Karratha,0,AU,1569548213,15,-20.74,116.85,29.74,4.10
55,Ilulissat,0,GL,1569548214,35,69.22,-51.10,4.00,4.60
56,East London,0,ZA,1569548049,17,-33.02,27.91,18.14,2.24
59,Codrington,6,AU,1569548214,50,-28.95,153.24,27.00,4.10
60,Nemuro,20,JP,1569548214,42,43.32,145.57,19.00,0.50
65,Chifeng,32,CN,1569548215,21,42.27,118.96,21.94,3.35
66,Kroya,57,ID,1569548215,33,-6.50,108.06,34.24,3.68
67,Santiago del Estero,0,AR,1569548216,36,-27.80,-64.26,20.04,4.25
72,Busselton,94,AU,1569547962,47,-33.64,115.35,18.33,2.90
77,Harper,1,US,1569548217,45,30.30,-99.24,29.00,6.05
89,Birjand,0,IR,1569548219,13,32.86,59.22,21.00,6.20
90,West Wendover,1,US,1569548219,25,40.74,-114.07,25.00,3.65
91,Yulara,0,AU,1569548219,20,-25.24,130.99,29.00,2.60
94,Carnarvon,0,ZA,1569548196,18,-30.97,22.13,10.24,2.32
107,Tucumcari,1,US,1569548222,30,35.17,-103.73,27.00,4.60
113,Airai,0,TL,1569548223,46,-8.93,125.41,30.24,2.42
133,Arman,1,RU,1569548227,46,59.70,150.17,3.44,3.17
140,Riachao das Neves,3,BR,1569548224,30,-11.75,-44.91,22.14,1.12
151,Atwater,75,US,1569548229,40,37.35,-120.61,30.00,5.70
160,Nerchinskiy Zavod,1,RU,1569548231,41,51.31,119.61,18.24,5.04
166,Xining,0,CN,1569548232,42,36.62,101.77,20.00,2.37
176,Muli,0,CN,1569548234,43,28.08,109.56,26.84,1.32
...,...,...,...,...,...,...,...,...,...
352,Atbasar,100,KZ,1569548263,50,51.81,68.36,5.64,1.25
353,Central Point,1,US,1569548263,32,42.38,-122.91,28.00,4.10
358,La Rioja,0,AR,1569548264,39,-29.41,-66.86,16.44,2.40
380,Bafq,0,IR,1569548268,12,31.60,55.40,20.04,1.66
381,Katobu,70,ID,1569548268,44,-4.94,122.53,32.34,3.17
383,Alice Springs,0,AU,1569548268,26,-23.70,133.88,27.00,2.10
387,Jalu,0,LY,1569548269,50,29.03,21.55,21.94,2.86
420,Caldwell,1,US,1569548274,35,43.67,-116.69,25.00,2.10
422,Vardo,1,US,1569548275,49,39.62,-77.74,22.00,3.60
423,Hervey Bay,40,AU,1569548275,47,-25.30,152.85,25.00,5.10
426,Digby,33,CA,1569548275,1,44.62,-65.76,16.11,1.34
435,Adrar,0,DZ,1569548277,9,27.87,-0.29,30.00,3.60
439,Kargil,0,PK,1569548278,43,34.56,76.13,9.64,2.31
440,Sar-e Pul,0,AF,1569548278,18,36.22,65.93,26.24,0.80
456,San Rafael,82,AR,1569548281,32,-34.61,-68.33,19.14,1.97
459,Flinders,0,AU,1569548281,24,-34.58,150.85,23.33,7.70
463,Kerman,0,IR,1569548282,14,30.29,57.06,15.00,1.00
483,Mehran,0,IR,1569548285,28,33.12,46.17,21.00,2.10
492,Madang,0,CN,1569548287,42,35.32,102.79,8.64,1.84
493,Pishin,0,PK,1569548287,44,30.58,67.00,22.64,0.35
503,Mecca,0,SA,1569548023,14,21.43,39.83,29.44,3.53
504,Beyneu,93,KZ,1569548289,35,45.32,55.19,11.14,7.26
507,Aswan,0,EG,1569548289,17,24.09,32.90,28.00,2.60
512,Xiangxiang,36,CN,1569548290,33,27.73,112.52,30.04,2.31
520,Katherine,0,AU,1569548291,31,-14.47,132.26,32.00,4.10
524,Herat,0,AF,1569548292,23,34.35,62.22,17.00,0.84
529,Mayo,75,CA,1569548293,36,63.59,-135.90,9.00,4.10
535,San Angelo,1,US,1569548014,36,31.46,-100.44,33.00,4.60
541,Noumea,75,NC,1569548000,42,-22.28,166.46,27.00,6.20
549,Baruun-Urt,49,MN,1569548296,25,46.68,113.28,21.34,9.92

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [29]:
hotels_df = chosen_pd[["City", "Country", "Lat", "Lng", "Humidity"]]
hotels_df.head()

                       City Country    Lat     Lng  Humidity
1                   Sarkand      KZ  45.41   79.91        27
14               Tymovskoye      RU  50.85  142.66        39
26  San Carlos de Bariloche      AR -41.13  -71.31        41
27             Grootfontein     NaN -19.56   18.10        33
30                Jamestown      AU -33.21  138.60        33

In [30]:
hotels_df["Hotel Name"]= ""
hotels_df.head()

/Users/Deborah/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

                       City Country    Lat     Lng  Humidity Hotel Name
1                   Sarkand      KZ  45.41   79.91        27
14               Tymovskoye      RU  50.85  142.66        39
26  San Carlos de Bariloche      AR -41.13  -71.31        41
27             Grootfontein     NaN -19.56   18.10        33
30                Jamestown      AU -33.21  138.60        33

In [31]:
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
#print(requests.get(base_url).json())
params = {"radius": 5000,
            "type": "hotels",
         "key": g_key}
hotel_names = []
for index, row in hotels_df.iterrows():
    params["location"]= f'{row["Lat"]},{row["Lng"]}'
    response = requests.get(base_url, params =params).json()
    
    results = response["results"]
print(results)
    #hotel_names.append(response["results"][0]["name"])
#print(hotel_names)

[{'geometry': {'location': {'lat': 46.6652838, 'lng': 113.2876804}, 'viewport': {'northeast': {'lat': 46.6986114, 'lng': 113.3168507}, 'southwest': {'lat': 46.6387118, 'lng': 113.2545376}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/geocode-71.png', 'id': 'a14539fa767ae18d239e3b677e1804bcad24131a', 'name': 'Baruun-Urt', 'place_id': 'ChIJ76UDTpLz5l0RwapxogwRSLw', 'reference': 'ChIJ76UDTpLz5l0RwapxogwRSLw', 'scope': 'GOOGLE', 'types': ['locality', 'political'], 'vicinity': 'Baruun-Urt'}, {'geometry': {'location': {'lat': 46.68399609999999, 'lng': 113.2815796}, 'viewport': {'northeast': {'lat': 46.68518958029149, 'lng': 113.2830152802915}, 'southwest': {'lat': 46.6824916197085, 'lng': 113.2803173197085}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png', 'id': '4798bc52ee97cbe7d926ae54925bec1a45f6f748', 'name': 'Хүнсний Дэлгүүр', 'place_id': 'ChIJ7S8bce3z5l0Rczc2l7w1BQA', 'plus_code': {'compound_code': 'M7MJ+HJ Baruun-Urt, Mongolia', 'global_code': '8PRMM7MJ+HJ'}, 'reference': 'ChIJ7S8bce3z5l0Rczc2l7w1BQA', 'scope': 'GOOGLE', 'types': ['convenience_store', 'food', 'point_of_interest', 'store', 'establishment'], 'vicinity': 'Baruun-Urt'}, {'geometry': {'location': {'lat': 46.6802293, 'lng': 113.2777575}, 'viewport': {'northeast': {'lat': 46.6813077302915, 'lng': 113.2791355302915}, 'southwest': {'lat': 46.6786097697085, 'lng': 113.2764375697085}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/generic_business-71.png', 'id': 'a63ca93fa9808d63b36c5ea04137e259f6e5f289', 'name': 'Jaakhan Sharga theatre', 'place_id': 'ChIJCxlzh5Lz5l0RemHdPSsNFDc', 'plus_code': {'compound_code': 'M7JH+34 Baruun-Urt, Mongolia', 'global_code': '8PRMM7JH+34'}, 'rating': 5, 'reference': 'ChIJCxlzh5Lz5l0RemHdPSsNFDc', 'scope': 'GOOGLE', 'types': ['point_of_interest', 'establishment'], 'user_ratings_total': 1, 'vicinity': 'Baruun-Urt - Tumentsogt Road, Baruun-Urt'}, {'geometry': {'location': {'lat': 46.6815328, 'lng': 113.270601}, 'viewport': {'northeast': {'lat': 46.6832264302915, 'lng': 113.2718878302915}, 'southwest': {'lat': 46.6805284697085, 'lng': 113.2691898697085}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/generic_business-71.png', 'id': 'fbb7f9f0760545e52d642f0c9d65b7589a3a6e6d', 'name': '"Цайрт" хотхон', 'photos': [{'height': 1365, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/101424567973273343720/photos">Bulgaa Erdene</a>'], 'photo_reference': 'CmRaAAAAqv49LIwbQmIduVsyoOqAHQVqO9JBqury5WjUb8ssukzJQ3Z1IYkNLeDNStkHBtamHiB4OE1HASQFz-_VfN6YHJVpegR_gp3tUkDCyRD6lsEOocY-tH5DzPt-9PvswHyIEhCTIJ8f2H0f_OQoYgCDMVeXGhS8iJ8BTK7jrO2PGL9ll84Jouge3g', 'width': 2048}], 'place_id': 'ChIJbR1jfozz5l0Rdh6EAW3P3tY', 'plus_code': {'compound_code': 'M7JC+J6 Baruun-Urt, Mongolia', 'global_code': '8PRMM7JC+J6'}, 'rating': 5, 'reference': 'ChIJbR1jfozz5l0Rdh6EAW3P3tY', 'scope': 'GOOGLE', 'types': ['point_of_interest', 'establishment'], 'user_ratings_total': 2, 'vicinity': 'Mongolia'}, {'geometry': {'location': {'lat': 46.6867343, 'lng': 113.2783498}, 'viewport': {'northeast': {'lat': 46.6879782302915, 'lng': 113.2797760802915}, 'southwest': {'lat': 46.6852802697085, 'lng': 113.2770781197085}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/school-71.png', 'id': '77213cebf178be3ac0846cddb9f4573c8f3a1278', 'name': 'Сүхбаатар аймаг 2-р сургууль', 'place_id': 'ChIJQz8JzPPz5l0RsNFxPrMswss', 'plus_code': {'compound_code': 'M7PH+M8 Baruun-Urt, Mongolia', 'global_code': '8PRMM7PH+M8'}, 'rating': 5, 'reference': 'ChIJQz8JzPPz5l0RsNFxPrMswss', 'scope': 'GOOGLE', 'types': ['school', 'point_of_interest', 'establishment'], 'user_ratings_total': 1, 'vicinity': 'Baruun-Urt'}, {'geometry': {'location': {'lat': 46.6652838, 'lng': 113.2876804}, 'viewport': {'northeast': {'lat': 46.6666327802915, 'lng': 113.2890293802915}, 'southwest': {'lat': 46.6639348197085, 'lng': 113.2863314197085}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png', 'id': 'c3dd289070df32c7bf903346cd7a38afc121a59b', 'name': 'Zotol zochid buudal', 'place_id': 'ChIJq6qqqqbz5l0R-wsh7h8fn74', 'plus_code': {'compound_code': 'M78Q+43 Baruun-Urt, Mongolia', 'global_code': '8PRMM78Q+43'}, 'rating': 5, 'reference': 'ChIJq6qqqqbz5l0R-wsh7h8fn74', 'scope': 'GOOGLE', 'types': ['restaurant', 'food', 'point_of_interest', 'establishment'], 'user_ratings_total': 1, 'vicinity': 'Baruun-Urt'}, {'geometry': {'location': {'lat': 46.6682306, 'lng': 113.2635301}, 'viewport': {'northeast': {'lat': 46.6695795802915, 'lng': 113.2648790802915}, 'southwest': {'lat': 46.66688161970851, 'lng': 113.2621811197085}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png', 'id': '06ccd50b70e3b6ce1c906001f26c21b9668bff98', 'name': 'Ахмадын амралт сувилал', 'place_id': 'ChIJQ_6AA4Pz5l0RQ3RMYzfzl-s', 'plus_code': {'compound_code': 'M797+7C Baruun-Urt, Mongolia', 'global_code': '8PRMM797+7C'}, 'reference': 'ChIJQ_6AA4Pz5l0RQ3RMYzfzl-s', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'vicinity': 'Baruun-Urt'}, {'geometry': {'location': {'lat': 46.6802307, 'lng': 113.2808721}, 'viewport': {'northeast': {'lat': 46.68158503029149, 'lng': 113.2823937302915}, 'southwest': {'lat': 46.67888706970849, 'lng': 113.2796957697085}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png', 'id': '47478f37f5edfa42ec6e40a9dcc1f6ac3724ad38', 'name': 'Сүхбаатар аймгийн нийгмийн даатгалын хэлтэс', 'opening_hours': {'open_now': True}, 'place_id': 'ChIJm84h55Lz5l0RSrIDNLXuk0U', 'plus_code': {'compound_code': 'M7JJ+38 Baruun-Urt, Mongolia', 'global_code': '8PRMM7JJ+38'}, 'rating': 3, 'reference': 'ChIJm84h55Lz5l0RSrIDNLXuk0U', 'scope': 'GOOGLE', 'types': ['point_of_interest', 'store', 'establishment'], 'user_ratings_total': 4, 'vicinity': 'Baruun'}, {'geometry': {'location': {'lat': 46.67956820000001, 'lng': 113.2792679}, 'viewport': {'northeast': {'lat': 46.6809051302915, 'lng': 113.2803944802915}, 'southwest': {'lat': 46.6782071697085, 'lng': 113.2776965197085}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/school-71.png', 'id': '92de8a756cebdef68aff3637ee15d80acb99c6ce', 'name': '3-р сургууль', 'opening_hours': {'open_now': True}, 'place_id': 'ChIJxSORWZLz5l0Rid7G6v5OIS4', 'plus_code': {'compound_code': 'M7HH+RP Baruun-Urt, Mongolia', 'global_code': '8PRMM7HH+RP'}, 'rating': 1, 'reference': 'ChIJxSORWZLz5l0Rid7G6v5OIS4', 'scope': 'GOOGLE', 'types': ['school', 'point_of_interest', 'establishment'], 'user_ratings_total': 1, 'vicinity': 'Baruun-Urt'}, {'geometry': {'location': {'lat': 46.6807729, 'lng': 113.2797583}, 'viewport': {'northeast': {'lat': 46.6821444802915, 'lng': 113.2811686802915}, 'southwest': {'lat': 46.6794465197085, 'lng': 113.2784707197085}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/generic_business-71.png', 'id': 'c5353d3f7295af5a853ce7162647b8681dcf2348', 'name': 'Гялс төгрөг ХЗХ', 'place_id': 'ChIJ8Q6h65Lz5l0RF7DfjlEzwSw', 'plus_code': {'compound_code': 'M7JH+8W Baruun-Urt, Mongolia', 'global_code': '8PRMM7JH+8W'}, 'rating': 5, 'reference': 'ChIJ8Q6h65Lz5l0RF7DfjlEzwSw', 'scope': 'GOOGLE', 'types': ['point_of_interest', 'establishment'], 'user_ratings_total': 1, 'vicinity': 'Баруун-Урт сум 7-р баг Таван-Эрдэнэ Худалдааны'}, {'geometry': {'location': {'lat': 46.6807759, 'lng': 113.2805067}, 'viewport': {'northeast': {'lat': 46.6822224302915, 'lng': 113.2818434302915}, 'southwest': {'lat': 46.6795244697085, 'lng': 113.2791454697085}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/generic_business-71.png', 'id': '90f5374cc6f52873ccbfeefbdbc37bcad90b9cfe', 'name': 'Sports Complex', 'photos': [{'height': 4608, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/106625034409753464998/photos">enkhbayar damdinjav</a>'], 'photo_reference': 'CmRaAAAAKdqvn0_rjpJ_USWFq0-U7VdUrSa0ed0EpxOlHjXk2W4SCD6BLRz-K9bDPMlQ_OH1so8hofzm4ZBYSl0lyoFT4JiuSPAyJ13Ah_hdrg15ynI971e7MS9VssQo4sD6kFpsEhCcFeNxj_2pWpNHRLA7YgCkGhQY0IJwxcxVsLfMlx5l2R8fzLGMiA', 'width': 3456}], 'place_id': 'ChIJebTm55Lz5l0RSYcGan88p7s', 'plus_code': {'compound_code': 'M7JJ+86 Baruun-Urt, Mongolia', 'global_code': '8PRMM7JJ+86'}, 'rating': 4.5, 'reference': 'ChIJebTm55Lz5l0RSYcGan88p7s', 'scope': 'GOOGLE', 'types': ['point_of_interest', 'establishment'], 'user_ratings_total': 4, 'vicinity': 'Baruun-Urt'}, {'geometry': {'location': {'lat': 46.68077950000001, 'lng': 113.2794714}, 'viewport': {'northeast': {'lat': 46.6821933802915, 'lng': 113.2808118302915}, 'southwest': {'lat': 46.6794954197085, 'lng': 113.2781138697085}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png', 'id': 'd6f3a1318ab994c36286fc73e352074aebf0d7ba', 'name': 'Таван эрдэнэ', 'photos': [{'height': 4160, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102007500166948348090/photos">Bayaraa Batbekh</a>'], 'photo_reference': 'CmRaAAAAK0VY_ll4kE19yL1W8Ar8m6OB5Py3MokLO86BgpZ4pmyK93x-247-L4rFYFYxJ3jydKP4rrNJFNcMH0u8n3cyasrieDUNy2NlsOZeYWGxwPI6fakEZZfQVRc9iSyTtNtjEhAsSwUJAmM9Z24n-znbDZJrGhSuw3tS9Wkv7n4o9yFtq4iz3kFtWg', 'width': 3120}], 'place_id': 'ChIJx-WtlJLz5l0RPu8qv58o34I', 'plus_code': {'compound_code': 'M7JH+8Q Baruun-Urt, Mongolia', 'global_code': '8PRMM7JH+8Q'}, 'rating': 5, 'reference': 'ChIJx-WtlJLz5l0RPu8qv58o34I', 'scope': 'GOOGLE', 'types': ['shopping_mall', 'point_of_interest', 'establishment'], 'user_ratings_total': 1, 'vicinity': 'Baruun-Urt'}, {'geometry': {'location': {'lat': 46.6806029, 'lng': 113.2788492}, 'viewport': {'northeast': {'lat': 46.68194613029149, 'lng': 113.2801127302915}, 'southwest': {'lat': 46.67924816970849, 'lng': 113.2774147697085}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/bank_dollar-71.png', 'id': 'e025361ea6d866096c8ed49cca2ae20641b16ff9', 'name': 'Bank of mongolia', 'photos': [{'height': 2448, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114888215013474949274/photos">khureltogoo adiya</a>'], 'photo_reference': 'CmRaAAAA9KEZt54bEmwMdS-HKEckPP10Ya9t-XRutkXCkWnTJ8pZPHSD_NDgGzgMf4K7MAIicu0Bu55OfgMYxRRm7HPZV79SXasi_TOv7qRP1uHhIX8u8yeIIFucjDqUwMgCOpg_EhALnzpwB_hBo4nuCPYp_SxIGhQXrIZOxHCvzkT1px3mzcqYVZQrNQ', 'width': 3264}], 'place_id': 'ChIJUZX3kZLz5l0RDgUOhYNmuZo', 'plus_code': {'compound_code': 'M7JH+6G Baruun-Urt, Mongolia', 'global_code': '8PRMM7JH+6G'}, 'rating': 5, 'reference': 'ChIJUZX3kZLz5l0RDgUOhYNmuZo', 'scope': 'GOOGLE', 'types': ['bank', 'finance', 'point_of_interest', 'establishment'], 'user_ratings_total': 1, 'vicinity': 'Baruun-Urt'}, {'geometry': {'location': {'lat': 46.6813095, 'lng': 113.2793051}, 'viewport': {'northeast': {'lat': 46.6826793302915, 'lng': 113.2808508802915}, 'southwest': {'lat': 46.6799813697085, 'lng': 113.2781529197085}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png', 'id': 'a0a5250d90e3356fe27cf6f64d2ab2f664df53ee', 'name': 'Smile', 'place_id': 'ChIJm0dEvJLz5l0RIiOCRW9vijg', 'plus_code': {'compound_code': 'M7JH+GP Baruun-Urt, Mongolia', 'global_code': '8PRMM7JH+GP'}, 'rating': 3.7, 'reference': 'ChIJm0dEvJLz5l0RIiOCRW9vijg', 'scope': 'GOOGLE', 'types': ['restaurant', 'food', 'point_of_interest', 'establishment'], 'user_ratings_total': 3, 'vicinity': 'Baruun-Urt'}, {'geometry': {'location': {'lat': 46.6793525, 'lng': 113.2780424}, 'viewport': {'northeast': {'lat': 46.68087413029151, 'lng': 113.2793728302915}, 'southwest': {'lat': 46.67817616970851, 'lng': 113.2766748697085}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/civic_building-71.png', 'id': '957478eb901cdbe643002f44d88d10317f79771d', 'name': 'Гэр бүл, хүүхэд, залуучуудын хөгжлийн газар', 'place_id': 'ChIJEc1CaJLz5l0RM7x6PmXSzkw', 'plus_code': {'compound_code': 'M7HH+P6 Baruun-Urt, Mongolia', 'global_code': '8PRMM7HH+P6'}, 'reference': 'ChIJEc1CaJLz5l0RM7x6PmXSzkw', 'scope': 'GOOGLE', 'types': ['local_government_office', 'point_of_interest', 'establishment'], 'vicinity': 'Baruun-Urt'}, {'geometry': {'location': {'lat': 46.68030479999999, 'lng': 113.2775831}, 'viewport': {'northeast': {'lat': 46.68190073029149, 'lng': 113.2788932802915}, 'southwest': {'lat': 46.67920276970849, 'lng': 113.2761953197085}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/generic_business-71.png', 'id': '25f27fbd757fba9df900725a88473b23c8a1fe1e', 'name': 'Baruun-Urt Theater', 'place_id': 'ChIJw2fOgJLz5l0RJ99uojNN4Hg', 'plus_code': {'compound_code': 'M7JH+42 Baruun-Urt, Mongolia', 'global_code': '8PRMM7JH+42'}, 'reference': 'ChIJw2fOgJLz5l0RJ99uojNN4Hg', 'scope': 'GOOGLE', 'types': ['point_of_interest', 'establishment'], 'vicinity': 'Baruun-Urt'}, {'geometry': {'location': {'lat': 46.68177439999999, 'lng': 113.2804333}, 'viewport': {'northeast': {'lat': 46.68313498029149, 'lng': 113.2821202802915}, 'southwest': {'lat': 46.68043701970849, 'lng': 113.2794223197085}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/generic_business-71.png', 'id': '14afdca9e9a7c48d207f88f8ac7a5c9ba8b5ac20', 'name': 'Nutgiin Udirdlagiin Ordon', 'place_id': 'ChIJwczxyZLz5l0RFSqo8b-Aqfg', 'plus_code': {'compound_code': 'M7JJ+P5 Baruun-Urt, Mongolia', 'global_code': '8PRMM7JJ+P5'}, 'reference': 'ChIJwczxyZLz5l0RFSqo8b-Aqfg', 'scope': 'GOOGLE', 'types': ['point_of_interest', 'establishment'], 'vicinity': 'Baruun-Urt'}, {'geometry': {'location': {'lat': 46.6812028, 'lng': 113.2780297}, 'viewport': {'northeast': {'lat': 46.6826845302915, 'lng': 113.2793525302915}, 'southwest': {'lat': 46.6799865697085, 'lng': 113.2766545697085}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png', 'id': '710040b8bcb29bb90b2ae69c88c798ad6d656e8c', 'name': 'Чимэг-2', 'opening_hours': {'open_now': True}, 'photos': [{'height': 540, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/112700941531596491691/photos">Otgonbayar Chuluunkhvv</a>'], 'photo_reference': 'CmRaAAAAeglACWZCbBAZ9QpSsKk7xylFVHElu7zrf3b2cYpwDDPmzyD2xcqn6Fxq9qm2jp37fursR25zgR39J9NHc2NrqJBF1MZnWaN6vwQzMGslFn7okCgCADgX3WEVZn0JhQlvEhApCGqZdRXjm98kb7aVTa53GhQpa2Imb1qJ0CjL59BlTSaDv_6JEQ', 'width': 720}], 'place_id': 'ChIJ5SCsY3Tz5l0RMJI6tjdhfGQ', 'plus_code': {'compound_code': 'M7JH+F6 Baruun-Urt, Mongolia', 'global_code': '8PRMM7JH+F6'}, 'rating': 1, 'reference': 'ChIJ5SCsY3Tz5l0RMJI6tjdhfGQ', 'scope': 'GOOGLE', 'types': ['clothing_store', 'point_of_interest', 'store', 'establishment'], 'user_ratings_total': 1, 'vicinity': 'Unnamed Road, Baruun-Urt'}, {'geometry': {'location': {'lat': 46.6813463, 'lng': 113.2780552}, 'viewport': {'northeast': {'lat': 46.6827587302915, 'lng': 113.2793916802915}, 'southwest': {'lat': 46.6800607697085, 'lng': 113.2766937197085}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/bank_dollar-71.png', 'id': '802d90086a223b164bd571a109fb622a9d477657', 'name': 'Khaan Bank ATM', 'photos': [{'height': 2317, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108631877015780232197/photos">dalmo pereira</a>'], 'photo_reference': 'CmRaAAAATvB7EzS5zd102pgCq-CWHIo1YiUSzj8oLQ3k1WJxlnhSLl8WeZnS1IjhpZvE_so3cmXhDZjdsyuuASfwZ1p6scDFg-WjYQUAy7mx34BNPvvJUfIxOvip6RO0b7wP3PGHEhBc2Cbk6zgnBL8ueL7aGmqMGhRGGnDH8KaZSt_8Ji6ayiX3pLm3Ag', 'width': 2695}], 'place_id': 'ChIJwaf-n5Lz5l0RPxdHrXxIcTQ', 'plus_code': {'compound_code': 'M7JH+G6 Baruun-Urt, Mongolia', 'global_code': '8PRMM7JH+G6'}, 'rating': 5, 'reference': 'ChIJwaf-n5Lz5l0RPxdHrXxIcTQ', 'scope': 'GOOGLE', 'types': ['bank', 'finance', 'point_of_interest', 'establishment'], 'user_ratings_total': 1, 'vicinity': 'Baruun-Urt'}, {'geometry': {'location': {'lat': 46.6811807, 'lng': 113.2775348}, 'viewport': {'northeast': {'lat': 46.6826507302915, 'lng': 113.2788599302915}, 'southwest': {'lat': 46.6799527697085, 'lng': 113.2761619697085}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png', 'id': 'ce67b6b7c8f07eaf5541e877627b1ce8a9ec17be', 'name': 'Deej', 'opening_hours': {'open_now': True}, 'photos': [{'height': 3096, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/113929197199872700275/photos">Soyoloo Batdorj</a>'], 'photo_reference': 'CmRaAAAAHPaYUGY96hlHg-W099HdfzklLRA_rWebm4i5dORFCxUweRkm9Sbzx47WZ7Q76_OM6YmMG7QbYwlpJEhghNu6SjRGy5iMjZBjT8F7Zf3X5SGZOsD75Y84m-eoCQ_Ma747EhDGkYouyncevnB1pEHo8-RWGhS9OaI_80t5siJdFM7hBW4SIrPhBg', 'width': 4128}], 'place_id': 'ChIJSdZmYY3z5l0R9UfdFMiInpU', 'plus_code': {'compound_code': 'M7JH+F2 Baruun-Urt, Mongolia', 'global_code': '8PRMM7JH+F2'}, 'rating': 4.4, 'reference': 'ChIJSdZmYY3z5l0R9UfdFMiInpU', 'scope': 'GOOGLE', 'types': ['shopping_mall', 'point_of_interest', 'establishment'], 'user_ratings_total': 7, 'vicinity': 'Baruun-Urt'}]

In [38]:

hotels_df.loc[index, "Hotel Name"] = results[0]['name']
hotels_df.head(10)

                       City Country    Lat     Lng  Humidity Hotel Name
1                   Sarkand      KZ  45.41   79.91        27
14               Tymovskoye      RU  50.85  142.66        39
26  San Carlos de Bariloche      AR -41.13  -71.31        41
27             Grootfontein     NaN -19.56   18.10        33
30                Jamestown      AU -33.21  138.60        33
34                    Yumen      CN  40.29   97.04        10
40            Mar del Plata      AR -46.43  -67.52        43
48                    Bluff      AU -23.58  149.07        31
51                 Cherskiy      RU  68.75  161.30        39
54                 Karratha      AU -20.74  116.85        15

In [26]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotels_df.iterrows()]
#hotel_info = [info_box_template.format(**row) for index, row in narrowed_city_df.iterrows()]
locations = hotels_df[["Lat", "Lng"]]

In [39]:
# Add marker layer ontop of heat map

#new_york_coordinates = (40.75, -74.00)
#fig = gmaps.figure(center=new_york_coordinates, zoom_level=2)
#heat_layer = gmaps.heatmap_layer(locations, weights="Humidity", dissipating=False, max_intensity=10, point_radius=2)

#Add layer
##fig.add_layer(heat_layer)
#fig

figure_layout = {'width': '400px',
                'height': '300px',
                'border': '1px solid black',
                'padding': '1px',
                'margin': '0 auto 0 auto'}
fig =gmaps.figure(layout=figure_layout)
markers =gmaps.marker_layer(locations)
fig.add_layer(markers)
# Display Map
fig

#fig =gmaps.figure()
#fig.add_layer(heat-layer)
#fig.add_layers(markers)
#fig

Figure(layout=FigureLayout(border='1px solid black', height='300px', margin='0 auto 0 auto', padding='1px', wi…